version: '3.7'

services:
    database:
        image: mariadb:${DB_VERSION}
        environment: 
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        container_name: ${DB_CONTAINER_NAME}
        restart: unless-stopped
        volumes: 
            - ./data_db/:/${DB_DATA}/
            - ./utils/:/utils/